server {
    listen 80;
    server_name localhost;

    # SPA routing
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Proxy all API requests to Backend
# Proxy API requests → loại bỏ prefix /api, proxy thẳng đến root của backend


    # Gateway API Proxy (Nếu cần) http://localhost:3003/admin/v1/stats/summary
    location /gateway-api/ {
        proxy_pass https://nda.trustid.com.vn/admin/v1/;
        proxy_ssl_server_name on;
        proxy_set_header Host nda.trustid.com.vn;
        proxy_set_header X-Real-IP $remote_addr;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
